---
- name: "Adding user to local group"
  hosts: all
  become: true
  gather_facts: false
  tasks: 
    - name: "Creating a local group"
      win_group:
         name: LocalGroup
         description: Allow access to C:/Developmenet folder 
    - name: "Creating a local user"
      win_user: 
        name: '{{item.name}}'
        password: '{{item.password}}'
        groups: LocalGroup
        update_password: false
        password_never_expires: true
      loop:
       - name: userA
         password: Pass123
       - name: userB
         password: Pass@123
    - name: "Creating Development folder"
      win_file:
        name: C:/Development
        state: Directory
        
    - name: "Setting Access Control List properties"
      win_acl:
        path: C:\Development
        rights: FullControl
        state: present
        type: allow
        user: LocalGroup 
    - name: Remove parent inheritance of Development folder
      win_acl_inheritance:
        path: C:\Development
        reorganize: true
        state: absent   
   
        
