---
- name: Install Apache and PHP
  hosts: all
  become: yes
  vars:
    php_packages:
      - php
      - php-gd
      - php-xml
    apache_packages:
      - httpd
  tasks:
    - name: Install PHP packages
      yum:
        name: "{{ php_packages }}"
        state: present
      tags: php

    - name: Install Apache packages
      yum:
        name: "{{ apache_packages }}"
        state: present
      tags: apache

    - name: Set environmental variables for Apache and PHP
      lineinfile:
        dest: /etc/environment
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^APACHE_HOME', line: 'APACHE_HOME=/usr/share/httpd' }
        - { regexp: '^PHP_HOME', line: 'PHP_HOME=/usr/bin' }
      tags: env

    - name: Restart Apache
      service:
        name: httpd
        state: restarted
      tags: apache
