---
- name: Java Installed or Not
  hosts: all
  gather_facts: False

  tasks:
   - name: Fetch Java version
     shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'                                                                                                                                   
     changed_when: False
     register: java_result
     failed_when: false

   - debug:
       msg: No Java or something failed.
     when: java_result.rc!=0

   - debug:
       msg: "Java {{ java_result.stdout }} already installed"
     when: java_result.rc==0
