---
- name: Create SSH connection to managed node
  hosts: all
  gather_facts: false
  vars:
    remote_user: basharat
    remote_host: 192.168.4.244

  tasks:
    - name: Generate SSH key
      ansible.builtin.openssh_keypair:
        path: ~/.ssh/id_rsa
        force: true

    - name: Add SSH key to authorized keys
      ansible.builtin.copy:
        content: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        dest: "~/.ssh/authorized_keys"
        mode: "0600"

    - name: Test SSH connection
      ansible.builtin.ping:
        remote_user: "{{ remote_user }}"
        remote_host: "{{ remote_host }}"
