---
- name: Check if Java is installed and install java if not
  hosts: all
  become: yes
  vars:
    java_package: openjdk-11-jdk  # Change to openjdk-11-jdk or other appropriate package name
  tasks:
    - name: Check if Java is already installed
      command: java -version
      register: java_version
      ignore_errors: yes

    - name: Install Java
      apt:
        name: "{{ java_package }}"
        state: present
      when: java_version.rc != 0

    - name: Set JAVA_HOME environment variable
      become: yes
      lineinfile:
        dest: /etc/environment
        regexp: '^JAVA_HOME='
        line: 'JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64'
        state: present
        create: yes

