---
- name: Check if Java is installed and install java if not
  hosts: all
  become: yes
  vars:
    java_package: openjdk-11-jdk  # Change to openjdk-11-jdk or other appropriate package name
  tasks:
     - name: Gather facts
      setup:
     
    - name: Display Python version if installed
      debug:
        var: ansible_facts.java_version
      when: ansible_facts.java_version is defined
      
    - name: Install Python if not installed
      apt:
        name: "{{java_package}}"
        state: present
      when: ansible_facts.java_version is not defined
      
    - name: Set JAVA_HOME environment variable
      become: yes
      lineinfile:
        dest: /etc/environment
        regexp: '^JAVA_HOME='
        line: 'JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64'
        state: present
        create: yes

