---
- name: SSH connection
  hosts: all
  become: true
  tasks:
    - name: Install Key...
      ansible.posix.authorized_key:
        user: root
        state: absent
        key: "{{lookup('file','/root/.ssh/id_rsa.pub')}}"
