---
- name: INSTALLING PACKAGES
  hosts: all
  tasks: 
   - name: Ensure Chocolatey itself is installed and use internal repo as source
     win_chocolatey:
          name:
           - chocolatey
           - chocolatey-core.extension
          state: present
