---
- name: Windows Firewall
  hosts: all
  tasks:
    - name: Disable Windows Firewall
      win_firewall:
        state: disabled
        profiles:
        - Domain
        - Private
        - Public
      tags: disable_firewall
